---
- ignore:
    name: "Redundant bracket"
    within:
      - "Kairos.convertTime"
      - "Kairos.currentDate"
      - "Kairos.dateString"
      - "Kairos.readConvertTime"
      - "Kairos.readInLocalTimeZone"
      - "Kairos.readTime"
      - "Kairos.readTimeString"
      - "Kairos.tzDatabaseToTZLabel"
      - "Kairos.tzString"

- ignore:
    name: "Avoid lambda"
    within:
      - "Params"
