---
resolver: nightly-2025-11-01
packages:
  - ./lib/core/
  - ./lib/exe/
ghc-options:
  "$locals":
    -Wall -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-deriving-strategies
    -Wmissing-export-lists
    -Wmissing-exported-signatures
    -Wmissing-home-modules
    -Wmissing-import-lists
    -Wpartial-fields
    -Wprepositive-qualified-module
    -Wredundant-constraints
    -Wunused-binds
    -Wunused-packages
    -Wunused-type-patterns
    -Wno-unticked-promoted-constructors
extra-deps:
  - env-guard-0.2@sha256:4251503bde7549e267bd307f4b293c8c0ac48c6585968108e3e3fc5a3cfbb179,1312
  - gitrev-typed-0.1@sha256:905b696dec9c52486290cfef2d3156420de83f5b21bfb0821a37822f40ee1568,3783
  - optparse-applicative-0.19.0.0@sha256:0b47b3ff7eb4a855b5f7d401690365fc62a32057374927ce0d478b620996222d,5813
  - git: https://github.com/tbidne/algebra-simple.git
    commit: 37ec7127fbd0f591d4539e4bf72a0badd7569181
  - git: https://github.com/tbidne/bounds.git
    commit: b7ca541cfdd8564bcebe5d38456fe7abf77885b8
  - git: https://github.com/tbidne/exception-utils.git
    commit: 61a9e06a26adcca70d565105a1508a16022435a2
  - git: https://github.com/tbidne/fs-utils.git
    commit: 26136275027fd827574c5004ebd11b659d7abdab
  - git: https://github.com/tbidne/monad-effects.git
    commit: bc18a934ac4a665024e0f47fcbf10c841fecbb13
    subdirs:
      - lib/effects-env
      - lib/effects-fs
      - lib/effects-ioref
      - lib/effects-optparse
      - lib/effects-terminal
      - lib/effects-time
  - git: https://github.com/tbidne/smart-math.git
    commit: 4e10a4134f825ba825113955bb97be7f7e28ad6e
allow-newer: true
