name: ci

on:
  push:
    branches:
      - main
      - release

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - vers: "9.2.8"
            proj-file: ""
          - vers: "9.4.8"
            proj-file: ""
          - vers: "9.6.6"
            proj-file: ""
          - vers: "9.8.2"
            proj-file: ""
          - vers: "9.10.1"
            proj-file: "--project-file cabal.ghc9101.project"
          - vers: "9.12.1"
            proj-file: ""
        os:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc.vers }}

      - name: Configure
        run: cabal configure ${{ matrix.ghc.proj-file }} --enable-tests --ghc-options -Werror

      - name: Compile
        run: cabal build ${{ matrix.ghc.proj-file }} kairos

      - name: Unit Tests
        run: cabal test ${{ matrix.ghc.proj-file }} kairos-core:unit --test-options "--hedgehog-tests 100000"

      - name: Functional Tests
        env:
          FUNC_EXTRA: ${{ matrix.os != 'windows-latest' && '1' }}
        run: cabal test ${{ matrix.ghc.proj-file }} kairos:functional

  stack:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true

      - name: Compile
        run: stack build kairos-core kairos --ghc-options -Werror

      - name: Test
        run: stack test kairos-core kairos --ghc-options -Werror

  nix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Compile & Test
        run: nix build
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable}}

      - name: Formatting
        run: |
          nix run .#format
          git diff --exit-code --color=always

  release:
    needs: [cabal, stack, nix, lint]
    if: github.ref == 'refs/heads/release'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - docker: false
            name: "macos-13"
            os: "macos-13"
            script: ".github/scripts/release_osx.sh"
            script_args: ""

          - docker: false
            name: "macos-14"
            os: "macos-14"
            script: ".github/scripts/release_osx.sh"
            script_args: ""

          - docker: false
            name: "ubuntu-latest"
            os: "ubuntu-latest"
            script: ".github/scripts/release_linux.sh"
            script_args: ""

          - docker: true
            name: "alpine_amd64"
            os: "ubuntu-latest"
            script: ".github/scripts/release_linux_static.sh"
            script_args: "alpine_amd64"

          - docker: false
            name: "windows-2019"
            os: "windows-2019"
            script: ".github/scripts/release_windows.sh"
            script_args: "2019"

          - docker: false
            name: "windows-2022"
            os: "windows-2022"
            script: ".github/scripts/release_windows.sh"
            script_args: "2022"

          - docker: false
            name: "windows-2025"
            os: "windows-2025"
            script: ".github/scripts/release_windows.sh"
            script_args: "2025"

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-docker-action@v4
        if: ${{ matrix.platform.docker == true }}

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.10.1"
          cabal-version: "3.12"

      - name: Install binary
        shell: bash
        run: |
          ${{ matrix.platform.script }} ${{ matrix.platform.script_args }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.platform.name }}
          path: bin

  merge:
    runs-on: "ubuntu-latest"
    needs: release
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: build-artifacts
          pattern: build-artifacts-*
          delete-merged: true
